# Generated by Django 4.0 on 2024-05-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coloring',
            name='type',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='likecoloring',
            unique_together={('coloring', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='liketheme',
            unique_together={('theme', 'user')},
        ),
    ]
