# Generated by Django 4.0 on 2024-05-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
