# Generated by Django 4.0 on 2024-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_usercoloring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoloring',
            name='image',
            field=models.ImageField(upload_to='user_colorings/', verbose_name='Цветная раскраска'),
        ),
    ]
