# Generated by Django 4.0 on 2024-05-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_delete_favourite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecoloring',
            options={'verbose_name': 'Like coloring', 'verbose_name_plural': 'Likes colorings'},
        ),
        migrations.AlterModelOptions(
            name='liketheme',
            options={'verbose_name': 'Like theme', 'verbose_name_plural': 'Likes themes'},
        ),
    ]
