# Generated by Django 4.0 on 2024-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_usercoloring_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoloring',
            name='coloring_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON раскраски'),
        ),
    ]
