# Generated by Django 4.0 on 2024-07-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_usercoloring_coloring_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='colorings/', verbose_name='Изображение'),
        ),
    ]
