# Generated by Django 4.0 on 2024-04-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_alter_category_description_alter_theme_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=None, verbose_name='Like')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_themes', to='models_app.theme', verbose_name='Тематика')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_users', to='models_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Like',
                'db_table': 'like',
            },
        ),
    ]
