# Generated by Django 4.0 on 2024-07-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
