# Generated by Django 4.0 on 2024-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_images/', verbose_name='Изображение пользователя'),
        ),
    ]
