# Generated by Django 4.0 on 2024-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Like'),
        ),
    ]
