# Generated by Django 4.0 on 2024-04-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_alter_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=None, verbose_name='Like'),
        ),
    ]
