# Generated by Django 4.0 on 2024-04-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_alter_like_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=None)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_themes', to='models_app.theme', verbose_name='Тематика')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_users', to='models_app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Favourite',
                'verbose_name_plural': 'Favourites',
                'db_table': 'favourites',
            },
        ),
    ]
