# Generated by Django 4.0 on 2024-04-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0010_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='status',
        ),
    ]
