# Generated by Django 4.0 on 2024-04-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0012_alter_like_options_remove_like_like_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeTheme',
        ),
    ]
